server:
  port: 8083

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/student/**
        - id: course
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/course/**
